name: 🚀 Tarea de Despliegue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Trabajo de Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener código
        uses: actions/checkout@v4

      - name: 📂 Subir por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-yeimi.alwaysdata.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs
          protocol: ftp
          log-level: standard
          exclude: |
            **/.git*
            **/.github/**
            .gitattributes
